import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to LoLPA Next!
        </h1>

        <p>
          Get started by checking out the {' '}
          <Link href="/champions"><a>Champions</a></Link> {' '}
          page
        </p>
      </main>
    </div>
  )
}
